version: "3.9"

services:
  web:
    build: .
    command: bin/dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - rails_db:/app/db
      - rails_storage:/app/storage
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_ice_cream
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rails_db:
  rails_storage:
  postgres_data:
