version: "3.9"
services:
  web:
    build: .
    container_name: rails_icecream_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
      DATABASE_URL: sqlite3:/app/storage/development.sqlite3
    command: >
      bash -c "bundle install && 
               bin/rails tailwindcss:build && 
               bin/rails db:prepare && 
               bin/rails db:seed:replant && 
               bundle exec rails s -b '0.0.0.0'"
